name = "metajul"
uuid = "ca897826-12de-4e40-9dbf-1888d61ae1b2"
authors = ["ajnebro <ajnebro@users.noreply.github.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
